### PR TITLE
Removing trailing spaces from sources

### LINKED ISSUE #1: Whitespace in Source column in values.csv
While `cldf validate` does not complain (I'd say this is a bug), trying to create an SQLite database from the CLDF dataset fails, because of trailing whitespace after source keys in `values.csv`, e.g.
```
$ cldf createdb cldf-atlas/ atlas.sqlite
INSERT INTO `ValueTable_SourceTable` (`ValueTable_cldf_id`,`SourceTable_id`,`context`) VALUES (?,?,?)
(('agua1253_Gend-01', 'jakway1996aguaruna ', '68'),)
Traceback (most recent call last):
...
  File "/home/robert/venvs/atlas/lib/python3.12/site-packages/csvw/db.py", line 109, in insert
    db.executemany(sql, rows)
sqlite3.IntegrityError: FOREIGN KEY constraint failed
```
There seem to be 32 such cases, see
```
$ csvgrep -c Source cldf-atlas/values.csv -m " ["| wc -l
33
```

### PR DESCRIPTION
**Pull request by davidainman**
These are errors in the original data entries, which were not caught by export scripts or cldf validate.

I have rerun derived features and checked cldf validate.

closes #1

### CODE REVIEW

**Comment by xrotwang** [comment]
One bibtex entry seems to be referred to with different case, again causing problems for the SQLite creation:
```
$ cldf createdb cldf-atlas/ atlas.sqlite
INSERT INTO `ValueTable_SourceTable` (`ValueTable_cldf_id`,`SourceTable_id`,`context`) VALUES (?,?,?)
(('muni1258_Attr-01', 'michaeletalndmuniche', '15'),)
```
There's only `michaeletalNDmuniche` in the BibTeX, but references for `michaeletalndmuniche` in `values.csv`:
```
$ csvcut -c Source cldf-atlas/values.csv | grep michaeletal
michaeletalndmuniche[15];gibson1996munichi[53-54]
gibson1996munichi[53-54];michaeletalndmuniche[15]
michaeletalndmuniche[15];gibson1996munichi[53-54]
michael2022pc;michaeletalNDmuniche[10-11]
michael2022pc;michaeletalNDmuniche[10-11]
michael2022pc;michaeletalNDmuniche[10-11]
michael2022pc;michaeletalNDmuniche[10-11]
michael2022pc;michaeletalNDmuniche[10-11]
```

Again, I'm a bit puzzled, why this isn't flagged by `cldf validate`. Will have to investigate in `pycldf`.

**Comment by xrotwang** [comment]
Ok, turns out bibtex keys being regarded case insensitive is expected behaviour: From https://docs.pybtex.org/api/parsing.html#pybtex.database.BibliographyData

> A dictionary of bibliography entries referenced by their keys. The dictionary is case insensitive

So, it's a bug in `pycldf`'s `createdb` command then. All good with this dataset :)

**Comment by davidainman** [comment]
It may be a good idea however to make them consistent in the underlying data. @nataliacp 

I note that this repo has already diverged from the dev repo. We are yoked to this one now.

**Comment by xrotwang** [comment]
> It may be a good idea however to make them consistent in the underlying data. @nataliacp

I agree - and I'm a bit embarassed not to have forced and specified this in the CLDF spec. I tend to use `grep` quite a bit for exploratory analysis of CLDF data, and having to remember to use the `-i` flag for some data but not for all is a pain.

**Pull request merged**
